board/blogs/urls.py
from django.urls import path
from .views import post_list,post_create,post_edit,post_delete, post_detail, post_like

app_name = 'blog'

urlpatterns = [
    path("", post_list, name="post_list"),
    path("create/", post_create, name="post_create"),
    path("detail/<int:post_id>", post_detail, name="post_detail"),
    path("edit/<int:post_id>", post_edit, name="post_edit"),
    path("delete/<int:post_id>", post_delete, name="post_delete"),
    path("likes/<int:post_id>", post_like, name="post_like"),
]

board/board/urls.py
from django.urls import path
from .views.base_views import (question_detail,index,)
from .views.question_views import (    
    question_create,
    question_edit,
    question_delete,
    vote_question,
    )
from .views.answer_views import (
    answer_create,
    answer_edit,
    answer_delete,
    vote_answer,
    )
from .views.comment_views import (
    comment_create_question,
    comment_edit_question,
    comment_delete_question,
    comment_create_answer,
    comment_edit_answer,
    comment_delete_answer,
    )

app_name = "board"

urlpatterns = [
    path("",index, name="index"),
    path("<int:qid>/",question_detail, name="detail"),

    path("question/create/",question_create, name="question_create"),
    path("question/modify/<int:qid>/",question_edit, name="question_modify"),
    path("question/delete/<int:qid>/",question_delete, name="question_delete"),
    
    path("answer/create/<int:qid>/", answer_create, name="answer_create"),
    path("answer/modify/<int:aid>/", answer_edit, name="answer_modify"),
    path("answer/delete/<int:aid>/", answer_delete, name="answer_delete"),

    path("comment/create/question/<int:qid>/", comment_create_question, name="comment_create_question"),
    path("comment/edit/question/<int:comment_id>/", comment_edit_question, name="comment_edit_question"),
    path("comment/delete/question/<int:comment_id>/", comment_delete_question, name="comment_delete_question"),
    path("comment/create/answer/<int:aid>/", comment_create_answer, name="comment_create_answer"),
    path("comment/edit/answer/<int:comment_id>/", comment_edit_answer, name="comment_edit_answer"),
    path("comment/delete/answer/<int:comment_id>/", comment_delete_answer, name="comment_delete_answer"),

    path("vote/question/<int:qid>/", vote_question, name="vote_question"),
    path("vote/answer/<int:aid>/", vote_answer, name="vote_answer"),
]

board/config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views.base_views import index

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include("board.urls")),
    path('users/', include("users.urls")),
    path('blogs/', include("blogs.urls")),
    path("", index, name="index")
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

board/board/models.py
from django.db import models
from django.contrib.auth.models import User

# Question, Answer 모델에서 author, voter 두 개의 필드가 User 모델 참조
# user.question_set 이렇게 Question 모델에 접근할 때 어느 필드가 기준이냐?

# Question table
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="author_question")
    subject = models.CharField(max_length=200, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(verbose_name="수정날짜", null=True, blank=True)
    voter = models.ManyToManyField(User, related_name="voter_question")
    view_cnt = models.BigIntegerField(default=0)

    def __str__(self) -> str:
        return self.subject
    
# Answer table
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,  related_name="author_answer")
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(verbose_name="수정날짜", null=True, blank=True)
    voter = models.ManyToManyField(User, related_name="voter_answer")

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="작성자")
    content = models.TextField(verbose_name="댓글내용")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(verbose_name="수정날짜", null=True, blank=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True, blank=True)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True, blank=True)

class QuestionCount(models.Model):
    """
    조회수 업데이트를 위한 모델
    사용자의 ip 저장
    """
    ip = models.CharField(max_length=30)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.ip

board/board/forms.py
from .models import Question, Answer, Comment
from django import forms

class NameForm(forms.Form):
    # 화면에 보여줄 요소
    name = forms.CharField(
        label="name", max_length=100, error_messages={"required":"이름입력"}
    )

class QuestionForm (forms.ModelForm):
    class Meta:
        model = Question
        fields = ["subject", "content"]
    
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["content"]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

board/board/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from ..models import Question, Answer
from ..forms import AnswerForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages

#######답변
@login_required(login_url="users:login")
def answer_create(request, qid):

    # question = get_object_or_404(Question, id=qid)
    # question.answer_set.create(content=request.POST["content"])

    question = get_object_or_404(Question, id=qid)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer=form.save(commit=False)
            answer.question = question
            answer.author = request.user
            answer.save()
            # detail 앵커 이용
            return redirect("{}#answer_{}".format(resolve_url("board:detail",qid=qid), answer.id))
    else:
        form = AnswerForm()
    context = {"question": question, "form": form}
    return render(request, "board/question_detail.html", context)

@login_required(login_url="users:login")
def answer_edit(request, aid):
    answer = get_object_or_404(Answer, id=aid)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modified_at = timezone.now()
            answer.save()
            return redirect("board:detail", answer.question_id)
    else:
        form = AnswerForm(instance=answer)

    return render(request, "board/answer_edit.html", {"form":form})

@login_required(login_url="users:login")
def answer_delete(request, aid):
    answer = get_object_or_404(Answer, id=aid)
    answer.delete()
    return redirect("board:detail", answer.question_id)

@login_required(login_url="users:login")
def vote_answer(request, aid):
    answer = get_object_or_404(Answer, id=aid)
    qid = answer.question.id
    if answer.author==request.user:
        messages.error(request, "본인이 작성한 댓글은 추천할 수 없습니다.")
    else:
        answer.voter.add(request.user)
    return redirect("board:detail", qid=qid)

board/board/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question, QuestionCount
from django.core.paginator import Paginator
from ..tools.utils import get_client_ip

from django.db.models import Q, Count

def index(request):
    page = request.GET.get('page',1)
    keyword = request.GET.get("keyword","")
    sort = request.GET.get("sort","recent")

    if sort =="recommend":
        question_list = Question.objects.annotate(num_voter = Count("voter")).order_by("-num_voter","-created_at")
    elif sort =="popular":
        question_list = Question.objects.annotate(num_answer = Count("answer")).order_by("-num_answer","-created_at")
    else:
        question_list = Question.objects.order_by("-created_at")

    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains = keyword)|
            Q(content__icontains = keyword)|
            Q(author__username__icontains = keyword)|
            Q(answer__author__username__icontains = keyword)
        ).distinct()

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {"question_list": page_obj, "page":page, "keyword":keyword, "sort":sort}

    return render(request, "board/question_list.html", context)

def question_detail(request, qid):
    page = request.GET.get('page')
    keyword = request.GET.get("keyword")
    sort = request.GET.get("sort")

    question = get_object_or_404(Question, id=qid)
    
    # 조회수 증가
    # client ip 가져오기
    ip = get_client_ip(request)

    cnt = QuestionCount.objects.filter(ip=ip, question=question).count()

    if cnt == 0:
        # QuestionCount 테이블에 ip와 question 추가
        qc = QuestionCount(ip=ip, question=question)
        qc.save()
        if question.view_cnt:
            question.view_cnt += 1
        else:
            question.view_cnt = 1
        question.save()


    context = {
        "question":question,
        "page":page,
        "keyword":keyword,
        "sort":sort,
        }

    return render(request, "board/question_detail.html", context)

board/board/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from ..models import Question, Answer, Comment
from ..forms import CommentForm

from django.contrib.auth.decorators import login_required
from django.utils import timezone

#######질문 댓글
@login_required(login_url="users:login")
def comment_create_question(request, qid):
    question = get_object_or_404(Question, id=qid)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.question = question
            comment.save()
            # return redirect("board:detail", qid = qid)
            # name 앵커 이용
            return redirect("{}#comment_{}".format(resolve_url("board:detail",qid=qid), comment.id))

    else:
        form = CommentForm()

    return render(request, "board/comment_form.html",{"form":form})

@login_required(login_url="users:login")
def comment_edit_question(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modified_at = timezone.now()
            comment.save()
            return redirect("{}#comment_{}".format(resolve_url("board:detail",qid=comment.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)

    return render(request, "board/comment_form.html",{"form":form})

@login_required(login_url="users:login")
def comment_delete_question(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect("board:detail", qid = comment.question.id)

#######답변 댓글
@login_required(login_url="users:login")
def comment_create_answer(request, aid):
    answer = get_object_or_404(Answer, id=aid)
    qid = answer.question.id
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.answer = answer
            comment.save()
            # name 앵커 이용
            return redirect("{}#comment_{}".format(resolve_url("board:detail",qid=qid), comment.id))

    else:
        form = CommentForm()

    return render(request, "board/comment_form.html",{"form":form})

@login_required(login_url="users:login")
def comment_edit_answer(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            qid = comment.answer.question.id
            comment.modified_at = timezone.now()
            comment.save()
            return redirect("{}#comment_{}".format(resolve_url("board:detail",qid=qid), comment.id))
    else:
        form = CommentForm(instance=comment)

    return render(request, "board/comment_form.html",{"form":form})

@login_required(login_url="users:login")
def comment_delete_answer(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    qid = comment.answer.question.id
    comment.delete()
    return redirect("board:detail", qid = qid)

board/board/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect
from ..models import Question
from ..forms import QuestionForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils import timezone

#######질문
@login_required(login_url="users:login")
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            return redirect("board:index")
    else:
        form = QuestionForm()

    return render(request, "board/question_create.html",{"form":form})

@login_required(login_url="users:login")
def question_edit(request, qid):
    question = get_object_or_404(Question, id=qid)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modified_at = timezone.now()
            question.save()
            return redirect("board:detail", qid)
        
    else:
        form = QuestionForm(instance=question)

    return render(request, "board/question_edit.html" , {"form":form})

@login_required(login_url="users:login")
def question_delete(request, qid):
    question = get_object_or_404(Question, id=qid)
    question.delete()
    return redirect("board:index")

@login_required(login_url="users:login")
def vote_question(request, qid):
    question = get_object_or_404(Question, id=qid)
    if question.author==request.user:
        messages.error(request, "본인이 작성한 글은 추천할 수 없습니다.")
    else:
        question.voter.add(request.user)
    return redirect("board:detail", qid=qid)

board/templates/board/answer_edit.html
{% extends 'base.html' %}
{% block contents %}
  <h5 class="my-3 border-bottom pb-2">답변 수정</h5>
  <!-- views.py is_valid() 통과 못할 때-->
  {% include 'errors.html' %}
  <form method="post" class="my-3">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="content"></label>
      <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
    </div>
    <input type="submit" value="답변수정" class="btn btn-success">
  </form>
{% endblock contents %}

{{form.as_p}}

board/templates/board/comment_form.html
{% extends 'base.html' %}
{% block contents %}
  <h5 class="my-3 border-bottom pb-2">댓글</h5>
  <!-- views.py is_valid() 통과 못할 때-->
  {% include 'errors.html' %}
  <form method="post" class="my-3">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="content"></label>
      <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
    </div>
    <input type="submit" value="댓글작성" class="btn btn-success">
  </form>
{% endblock contents %}

{{form.as_p}}

board/templates/board/question_create.html
{% extends 'base.html' %}
{% block contents %}
  <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
  <!-- views.py is_valid() 통과 못할 때-->
  {% include 'errors.html' %}
  <form method="post" class="my-3">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="subject">제목</label>
      <input type="text" name="subject" id="subject" class="form-control" value="{{form.subject.value|default_if_none:''}}">
    </div>
    <div class="form-group mb-3">
      <label for="content"></label>
      <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
    </div>
    <input type="submit" value="질문등록" class="btn btn-success">
  </form>
{% endblock contents %}

{{form.as_p}}

board/templates/board/question_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block style %}

  <style>
    .comment {
      border-top: dotted 1px #ddd;
      font-size: 0.7em;
    }
  </style>
{% endblock style %}
{% block contents %}
  <h2 class="border-bottom py-2">
    <!--질문제목-->
    {{question.subject}}
  </h2>
  <!--추천 영역-->
  <div class="row my-3">
    <!-- 자신의 글 추천할 수 없음 메세지 영역 -->
    {% if messages %}
      <div class="alert alert-danger my-3">
        {% for msg in messages %}
          <strong>{{msg.tags}}</strong>
          <ul>
            <li>{{msg.message}}</li>
          </ul>
        {% endfor %}
      </div>
    {% endif %}
    <div class="col-1">
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
        <!-- 추천 수 -->
        {{question.voter.count}}
      </div>
      <div class="d-grid d-block">
        <a href="{% url 'board:vote_question' question.id %}" class="recommend btn btn-sm btn-secondary">추천</a>
      </div>
    </div>
    <div class="col-11">
      <div class="card">
        <div class="card-body">
          <div class="card-text">
            <!--질문내용-->
            {{question.content}}
          </div>
          <div class="d-flex justify-content-end">
            <div class="badge text-bg-light p-2 text-start">
              <!--작성자-->
              <div class="mb-2">
                {{question.author}}
              </div>
              <!--질문작성날짜-->
              {{question.created_at}}
            </div>
          </div>
          <!--수정 날짜-->
          <div class="d-flex justify-content-end">
            {% if question.modified_at %}
              <div class="badge text-bg-light p-2 text-start">
                <!--작성자-->
                <div class="mb-2">modified_at</div>
                <!--질문수정날짜-->
                {{question.modified_at|date}}
              </div>
            {% endif %}
          </div>
          <!--// 수정 날짜 종료-->
          <!-- 로그인 사용자와 작성자가 동일한 경우만 -->
          {% if request.user == question.author %}
            <div class="my-3">
              <a href="{% url 'board:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
              <a href="{% url 'board:question_delete' question.id %}" class="delete btn-sm btn-outline-secondary">삭제</a>
            </div>
          {% endif %}
          <!-- 질문 댓글 영역 -->
          {% if question.comment_set.count > 0 %}
            <div class="mt-3">
              {% for comment in question.comment_set.all %}
                <a name="comment_{{comment.id}}"></a>
                <div class="comment py-2 text-muted">
                  <span style="white-space:pre-line">{{comment.content}}</span>
                  <span>
                    <!--댓글 작성자 / 작성일시 / 수정일시-->
                    -
                    {{comment.author}},
                    {{comment.created_at}}
                    {% if comment.modified_at %}
                      (수정 :
                      {{comment.modified_at|date}})
                    {% endif %}
                  </span>
                  {% if request.user == comment.author %}
                    <a href="{% url 'board:comment_edit_question' comment.id%}" class="small">수정</a>
                    <a href="{% url 'board:comment_delete_question' comment.id%}" class="small delete">삭제</a>
                  {% endif %}
                </div>
              {% endfor %}
            </div>
          {% endif %}
        </div>
        <div class="mx-3">
          <a href="{% url 'board:comment_create_question' question.id%}" class="small">댓글추가....</a>
        </div>
      </div>
    </div>
  </div>
  <!-- Answer 영역 question과 answer 외래키 제약조건 상태 question.answer_set question.answer_set.count : question에 달린 댓글 개수 question.answer_set.all : question에 달린 댓글 전체 -->

  <!-- Answer 영역 -->
  <h5 class="border-bottom py-2 my-3">
    <!--답변 개수-->
    {{question.answer_set.count}}
    개의 답변이 있습니다.
  </h5>
  {% for answer in question.answer_set.all %}
    <a name="answer_{{answer.id}}"></a>
    <!--추천 영역-->
    <div class="row my-3">
      <div class="col-1">
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
          <!-- 추천 수 -->
          {{answer.voter.count}}
        </div>
        <div class="d-grid d-block">
          <a href="{% url 'board:vote_answer' answer.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
      </div>
      <div class="col-11">
        <div class="card">
          <div class="card-body">
            <div class="card-text">
              <!--답변내용-->
              {{answer.content}}
            </div>
            <div class="d-flex justify-content-end">
              <div class="badge text-bg-light p-2 text-start">
                <!--답변 작성자-->
                <div class="mb-2">
                  {{answer.author}}
                </div>
                <!--답변 작성날짜-->
                {{answer.created_at}}
              </div>
            </div>
            <!--답변 수정 날짜-->
            <div class="d-flex justify-content-end">
              {% if answer.modified_at %}
                <div class="badge text-bg-light p-2 text-start">
                  <!--작성자-->
                  <div class="mb-2">modified_at</div>
                  <!--답변수정날짜-->
                  {{answer.modified_at|date}}
                </div>
              {% endif %}
            </div>
            <!--// 답변 날짜 종료-->
            {% if request.user == answer.author %}
              <div class="my-3">
                <a href="{% url 'board:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="{% url 'board:answer_delete' answer.id %}" class="delete btn-sm btn-outline-secondary">삭제</a>
              </div>
            {% endif %}
            <!-- 답변 댓글 영역 -->

            {% if answer.comment_set.count > 0 %}
              <div class="mt-3">
                {% for comment in answer.comment_set.all %}
                  <a name="comment_{{comment.id}}"></a>
                  <div class="comment py-2 text-muted">
                    <span style="white-space:pre-line">{{comment.content}}</span>
                    <span>
                      <!--댓글 작성자 / 작성일시 / 수정일시-->
                      -
                      {{comment.author}},
                      {{comment.created_at}}
                      {% if comment.modified_at %}
                        (수정 :
                        {{comment.modified_at|date}})
                      {% endif %}
                    </span>
                    {% if request.user == comment.author %}
                      <a href="{% url 'board:comment_edit_answer' comment.id%}" class="small">수정</a>
                      <a href="{% url 'board:comment_delete_answer' comment.id%}" class="small delete">삭제</a>
                    {% endif %}
                  </div>
                {% endfor %}
              </div>
            {% endif %}

          </div>
          <div class="mx-3">
            <a href="{% url 'board:comment_create_answer' answer.id%}" class="small">댓글추가....</a>
          </div>
        </div>
      </div>
    </div>

  {% endfor %}

  <div>
    <a href="{% url 'board:index' %}" class="btn btn-sm btn-primary">목록으로</a>
  </div>
  <form action="{% url 'board:answer_create' question.id %}" method="post" class="my-3">
    {% include 'errors.html' %}
    {% csrf_token %}
    <div class="form-group mb-3">
      <textarea name="content" id="content" rows="10" class="form-control"></textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-success" {% if not user.is_authenticated %} disabled="disabled" {% endif %}>
  </form>

  <form action="{% url 'board:index' %}" method="get" id="actionForm">
    <input type="hidden" name="keyword" value="{{keyword|default_if_none:''}}" id="keyword">
    <input type="hidden" name="page" value="{{page}}" id="page">
    <input type="hidden" name="sort" value="{{sort}}" id="sort">
  </form>

{% endblock contents %}
{% block script %}
  <script src="{% static 'js/detail.js' %}"></script>
{% endblock script %}

board/templates/board/question_edit.html
{% extends 'base.html' %}
{% block contents %}
  <h5 class="my-3 border-bottom pb-2">질문 수정</h5>
  <!-- views.py is_valid() 통과 못할 때-->
  {% include 'errors.html' %}
  <form method="post" class="my-3">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="subject">제목</label>
      <input type="text" name="subject" id="subject" class="form-control" value="{{form.subject.value|default_if_none:''}}">
    </div>
    <div class="form-group mb-3">
      <label for="content"></label>
      <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
    </div>
    <input type="submit" value="질문수정" class="btn btn-success">
  </form>
{% endblock contents %}

{{form.as_p}}

board/templates/board/question_list.html
{% extends 'base.html' %}
{% load static %}
{% load board_filter %}
{% load humanize %}
{% block contents %}
  <div class="my-3">
    <div class="row mt-3 justify-content-between">
      <div class="col-md-3">
        <select class="form-control so">
          <option value="recent" {% if sort == 'recent' %}selected{% endif %}>최신순</option>
          <option value="recommend" {% if sort == 'recommend' %}selected{% endif %}>추천순</option>
          <option value="popular" {% if sort == 'popular' %}selected{% endif %}>인기순</option>
        </select>
      </div>
      <div class="col-md-8">
        <div class="input-group mb-3">
          <input type="text" name="" id="top_keyword" class="form-control" value="{{keyword|default_if_none:''}}">
          <button class="btn btn-outline-secondary" type="submit" id="btn_search">찾기</button>
        </div>

      </div>
    </div>

    <table class="table">
      <thead>
        <tr class="table-success">
          <th scope="col">번호</th>
          <th scope="col">추천</th>
          <th scope="col">제목</th>
          <th scope="col">조회수</th>
          <th scope="col">작성자</th>
          <th scope="col">작성일시</th>
        </tr>
      </thead>
      <tbody>
        {% if question_list %}
          {% for question in question_list %}
            <tr>
              <tr>
                <th scope="row">{{question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1}}</th>
                <td>
                  <!-- 질문 추천 수 -->
                  {% if question.voter.all.count %}
                    <span class="badge text-bg-warning px-2 py-1">
                      {{question.voter.all.count}}
                    </span>
                  {% endif %}
                </td>
                <td>
                  <a href="{% url 'board:detail' qid=question.id%}" class="text-decoration-none text-dark">
                    {{question.subject}}
                    <!-- 질문에 달린 답변의 개수 표시 -->
                    {% if question.answer_set.count > 0 %}
                      <span class="text-danger small mx-2">
                        {{question.answer_set.count}}
                      </span>
                    {% endif %}
                  </a>
                </td>
                <td>{{question.view_cnt}}</td>
                <td>{{question.author}}</td>
                {% comment %} <td>{{question.created_at|date}}</td> {% endcomment %}
                <td>{{question.created_at|naturaltime}}</td>
              </tr>
            {% endfor %}
          {% else %}
            <tr>
              <td colspan="3">질문이 없습니다.</td>
            </tr>
          {% endif %}
        </tbody>
      </table>
      <nav aria-label="...">
        <ul class="pagination justify-content-center">
          {% if question_list.has_previous %}
            <li class="page-item">
              <a class="page-link" href="{{question_list.previous_page_number}}">Previous</a>
            </li>
          {% endif %}

          {% for page in question_list.paginator.page_range %}
            {% if page >= question_list.number|add:-5 and page <= question_list.number|add:5%}
              <li class="page-item {% if page == question_list.number %}active{% endif %}" aria-current="page">
                <a class="page-link" href="{{page}}">{{page}}</a>
              </li>
            {% endif %}
          {% endfor %}

          {% if question_list.has_next %}
            <li class="page-item">
              <a class="page-link" href="{{question_list.next_page_number}}">Next</a>
            </li>
          {% endif %}
        </ul>
      </nav>
      <div>
        <a href="{% url 'board:question_create' %}" class="btn btn-primary">질문 등록</a>
      </div>
    </div>
    <!--페이지 번호 클릭 시 이동할 폼-->
    <form action="{% url 'board:index' %}" method="get" id="actionForm">
      <input type="hidden" name="keyword" value="{{keyword|default_if_none:''}}" id="keyword">
      <input type="hidden" name="page" value="{{page}}" id="page">
      <input type="hidden" name="sort" value="{{sort}}" id="sort">
    </form>
  {% endblock contents %}
  {% block script %}
    <script src="{% static 'js/list.js' %}"></script>
  {% endblock script %}